spring:
  config:
    import:
      - "aws-parameterstore:/popnup/prod/"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.popnup: info

management:
  endpoint:
    health:
      show-details: never

