spring:
  datasource:
    url: jdbc:h2:mem:popnup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

logging:
  level:
    com.popnup: debug

naver:
  maps:
    client-id: xuw6b5ypsr
    client-secret: xYpDojd2SU54of2IboHi0fIRDOSr2J96LI9RKnYZ