spring:
  application:
    name: popnup

  profiles:
    active: local

  jpa:
    open-in-view: false

  # 네이버 지도 API 공동 설정 추가
  naver:
    maps:
      client-id: xuw6b5ypsr
      client-secret: xYpDojd2SU54of2lboHi0fIRDOSr2J96Ll9RKnYZ


jwt:
  secret: c29tZS1qd3Qtc2VjcmV0LWtleS1leGFtcGxlLWZvci1sb2NhbC10ZXN0aW5nLTIwMjY=