spring:
  application:
    name: popnup

  profiles:
    active: local

  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:cG9wbnVwLXNlY3JldC1rZXktZm9yLXRlc3QtZW52aXJvbm1lbnQtMjAyNi12ZXJ5LXNhZmUtYW5kLXNlY3VyZQ==}

  # 네이버 지도 API 공동 설정 추가
  naver:
    maps:
      client-id: xuw6b5ypsr
      client-secret: xYpDojd2SU54of2lboHi0fIRDOSr2J96Ll9RKnYZ
